name: stundenplan
description: Stundenplan app für das HAG

publish_to: 'none'

version: 1.6.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^2.2.0
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.9.0
  google_fonts: ^2.0.0
  html: ^0.15.0
  http: ^0.13.2
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.1
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.5
  time_ago_provider: ^4.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  yaml: ^3.1.0
  icalendar_parser : ^1.0.0
  image_picker: ^0.8.4
  google_ml_kit: ^0.7.2
  flutter_secure_storage: ^5.0.2
  rrule: ^0.2.3
  flutter_nearby_connections: ^1.1.1
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  image: ^3.1.1
  opencv: ^1.0.4
  cryptography: ^2.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_foreground : "adaptive_icon_foreground.png"
  adaptive_icon_background : "adaptive_icon_background.png"

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.3

flutter:
  uses-material-design: true
  assets:
    - assets/models/
