name: stundenplan
description: Stundenplan app für das HAG

publish_to: 'none'

version: 1.8.7+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^4.0.2
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^5.1.0
  html: ^0.15.0
  http: ^1.1.0
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pull_to_refresh_flutter3: ^2.0.1
  shared_preferences: ^2.0.15
  time_ago_provider: ^4.1.2
  tuple: ^2.0.0
  url_launcher: ^6.1.7
  yaml: ^3.1.1
  icalendar_parser: ^2.0.0
  image_picker: ^1.0.2
  cookie_jar: ^4.0.8
  flutter_secure_storage: ^8.0.0
  rrule: ^0.2.10
  workmanager: ^0.5.1
  flutter_local_notifications: ^15.1.0+1
  device_info_plus: ^9.0.3
  collection: ^1.16.0
  clock: ^1.1.1
  archive: ^3.3.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_foreground : "adaptive_icon_foreground.png"
  adaptive_icon_background : "adaptive_icon_background.png"

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.4

flutter:
  uses-material-design: true
